### ISSUE TITLE
how to `dub fetch` latest when older package already exists?

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#1018]
how to `dub fetch` latest when older package already exists? (and without explicitly specifying which version is the latest)

```
dub list|grep dscanner
dscanner 0.3.0: /home/timothee/.dub/packages/dscanner-0.3.0/dscanner/
dub fetch dscanner
Please note that you need to use `dub run <pkgname>` or add it to dependencies of your package to actually use/run it. dub does not do actual installation of packages outside of its own ecosystem.
# doesn't do anything! and message not very informative
dub fetch dscanner --version=0.4.0-beta.3
Placing dscanner 0.4.0-beta.3 to /home/timothee/.dub/packages/...
```

**Comment by Geod24** [comment]
The issue was that the latest was not yet a release. We have the `--prerelease` option for `dub upgrade` but not for `dub fetch`. I think that is fine, as `dub fetch` is mostly intended to fetch binaries without running them. If a pre-release is desired, a specific version spec can be used. So closing as WONTFIX.
