### ISSUE TITLE
New feature: precompile dependency.

### ISSUE THREAD

**Issue by 9il** [dlang/dub#1020]
[Mir GLAS](https://github.com/libmir/mir-glas) should be always precompiled. It should be compiled with

```
dub build --config=static --build=target-native --compiler=ldmd2 --build-mode=singleFile --parallel
```

But can be used with any D compiler. GLAS requires mir-cpuid to be linked with.

For now D users can not use Mir GLAS as dependency.

**Comment by WebFreak001** [comment]
different compilers may break because of ABI changes.

To distribute regular static libraries, do the same you would like with a C library, e.g. either a separate build step command or downloading prebuilt libraries and linking them in as well as providing extra D code to interface with the public APIs.
