### ISSUE TITLE
Why not allow building packages with no source files ?

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#1035]
I am getting: `Configuration 'X' of package Y contains no source files`
However, why not allow building it? The point building to build a package that has dependencies on other packages (ie linker flags and imports won't be empty)

**Comment by s-ludwig** [comment]
The reason why the warning comes up is mostly because it would be pointless to create a static or dynamic library without any content. However, it should still attempt to built it.

The suggested way to implement pure meta packages that only contain dependencies is to use `"targetType": "none"`. That makes it clear that the intention really is to not have any code and avoids creating empty library files (`"targetType": "sourceLibrary"` would do the same, although this is mostly meant for pure header file packages).

**Comment by WebFreak001** [comment]
duplicate of https://github.com/dlang/dub/issues/97

fixed in https://github.com/dlang/dub/pull/1364
