### ISSUE TITLE
Add ability to specify the url path to code in dependencies

### ISSUE THREAD

**Issue by ilya-stromberg** [dlang/dub#104]
Please, add ability to specify the url path to code in dependencies.
Today we can specify the local path:

```
  "dependencies": {
      "mysql-native": {"version": "~master", "path": "path/to/package"}
  },
```

Please add url support, for example like this:

```
 {"version": "~master", "https": "https://github.com/rejectedsoftware/mysql-native.git"}
```

or this:

```
 {"version": "~master", "url": "https://github.com/rejectedsoftware/mysql-native.git"}
```

It can help if I fork project but don't add it to the dub database.

**Comment by jacob-carlborg** [comment]
Is there any status on this?

**Comment by timotheecour** [comment]
@s-ludwig I would really like to have this feature; any help would be greatly appreciated; eg, where would code need to be changed for this?
Thanks!

**Comment by s-ludwig** [comment]
Off the top of my head:
- `Dependency` needs to get a new `url` property of type `URL` - including update of `fromJson` and `toJson`
- The (de)serialization logic for `Dependency` in dub/recipe/sdl.d needs to be updated as well
- It would probably make sense to lower the `Dependency.path` property to `Dependency.url` (i.e. as `"file://"~path`) to be able to unify the high-level code
- `dependencyToJson` and `dependencyFromJson` of `SelectedVersions` need to be updated as well. Path based dependencies should continue to be output as `"path": "..."` for backwards compatibility
- Package manager needs to get overloads that operate on `URLs` in addition to `Path`s and needs a chaching/cloning logic for non-"file://" URLs

There are probably a few places where currently the `.path` property is used instead of `.url` that also need to be changed (e.g. `Project.collectDependencies`). But my hope (and I might overlook something) is that `PackageManager` is the only place where the real change needs to happen.

**Comment by timotheecour** [comment]
is anyone planning to work on this?

**Comment by Geod24** [comment]
I made a slightly different proposal at #1840 .
The idea is to support `git submodule` without having the URL added explicitly to the manifest file.
The reason not to add the URL explicitly is that we don't want packages on the registry using URL dependencies (feel free to argue on the issue, that's why it's there).

I've been using `git submodules` + path-based dependencies for a few years now, for the same reason mentioned here: the ability to override packages as necessary, or to even switch to a different provider for a library (we use a fork of vibe.d for example).

The proposition is however more tied to `git` and does not support SVN or Mercurial, as asked by https://github.com/dlang/dub/issues/104#issuecomment-24106457 , but there is currently no support for either tool.

**Comment by Geod24** [comment]
Done, we can now use `repository`.
