### ISSUE TITLE
dub run <package> blindy runs first package it can find in `.dub/packages` folder without regards to version

### ISSUE THREAD

**Issue by skoppe** [dlang/dub#1040]
In my case I have multiple versions of the unit-threaded package in the package folder.

What I need is to be able to specify the package version dub should run. E.g. like so:

`dub run unit-threaded@0.7.2`

**Comment by rjframe** [comment]
The dub.selections.json file in the project directory will do this. It's automatically generated when you build, then you can change the version manually. Checking this into your VCS would ensure that version is shared among everyone that works on the code.

Example file:

    {
        "fileVersion": 1,
        "versions": {
            "unit-threaded": "0.7.2",
            "other-dep": "x.y.z"
        }
    }

**Comment by skoppe** [comment]
`dub.selections.json` works 👍 But this issue is not related to that.

see https://github.com/skoppe/jazr/blob/master/dub.selections.json

The problem I have is when I want to run a different package than the one in the current working directory. `dub run <package>` supports this by running the package in your package folder. But as the title says, it just picks the first version it can find.

**Comment by Andrepuel** [comment]
+1 for this issue.
I've just had crypt errors using unit-threaded because the `gen_ut_main` command was using an older version of unit threaded than my project was linking against.

My solution was to added a subPackage to my project and copy the gen_ut_main.d file to this sub package. Then I've changed the preBuildCommands to `"dub run -c gen_ut_main -- -f bin/ut.d"`

**Comment by John-Colvin** [comment]
+1 dub should support `--version` on all commands that are about a specific package (run, build, test, generate, describe, clean, dustmite, fetch, remove, clean-caches & convert)

**Comment by FeepingCreature** [comment]
Is it me or does this make unit-threaded basically unusable? Since it runs `gen_ut_main`, it seems unit-threaded can never ever change the behavior of `gen_ut_main` because then everyone's unittest runners will break, regardless of what `dub.selections.json` says.

**Comment by skoppe** [comment]
It is very much usable. As serious as this version bug might be, it actually occurs very little in practice (people need to use `dub run`, they need to have multiple versions of the same package, the filesystem needs to return the old one, and there needs to be a breaking change). I have only run into this issue once or twice (I remember there was a breaking change with unit-threaded a couple years ago).

Still, just picking the first version in the packages folder is obviously the wrong thing to do, especially when there is a `dub.selection.json` file right there.

At this point I am rooting for robert's [dud](https://github.com/symmetryinvestments/dud) build tool though.

**Comment by WebFreak001** [comment]
on windows the filesystem APIs most likely return the directory as sorted list so this can happen extremely quickly as the lowest versions nearly always sort first.

Not all `dub run` tools might also be as backwards compatible as unit-threaded either.

I don't agree with it picking from dub.selections.json though, it feels much more like running a standalone tool instead of something affected by the current folder. Also you probably want to specify the tool as dependency too if you want `dub upgrade` to pick it up into the dub.selections.json which isn't really always what you want.

**Comment by FeepingCreature** [comment]
If it's not what you want, then don't put it in the dub.selections.json.

When you need the unit-threaded runner, unit-threaded will usually be in the dependencies anyways.
