### ISSUE TITLE
dependencies with a platform suffix is silently accepted and the suffix ignored

### ISSUE THREAD

**Issue by rtbo** [dlang/dub#1049]
On cross-platform dub packages that has e.g. a `"dependencies-linux"` entry in `dub.json`, dub tries to build the dependencies also on non-linux systems.
This makes building the package eventually fail if the dependency isn't meant to be built on a non-linux system.

**Comment by rtbo** [comment]
steps to reproduce from a Windows system:
```cmd
git clone https://github.com/rtbo/dub1049.git
cd dub1049
dub test
```

**Comment by s-ludwig** [comment]
I haven't run the repro case yet, but that behavior would really surprise me, because actually platform suffixes are not supported at all for dependencies. So it should really not include the dependency at all in this case (outputting a warning would be helpful but is not yet implemented).

The intended way to get this working is to define separate configurations for each platform and put the platform specific dependencies in there. DUB will then still *download* them, but will only build those that are specified by the selected configuration.

**Comment by rtbo** [comment]
If I understand, dub should not even try to download and build the linux specific dependency because this is not the correct way for specifying such dependency!

At least fixing my code will be easy, I will introduce configurations!

**Comment by Geod24** [comment]
Regarding the download issue, we have https://github.com/dlang/dub/issues/1706
But `dub` should either not take `dependencies` into account if it has a platform suffix, or honor it.

Changed the title accordingly.

**Comment by Geod24** [comment]
Should be fixed by https://github.com/dlang/dub/pull/2280

**Comment by Geod24** [comment]
This is essentially https://github.com/dlang/dub/issues/614 , closing as duplicate.
