### ISSUE TITLE
The unittest doesn't work for an application

### ISSUE THREAD

**Issue by Heromyth** [dlang/dub#1118]
Here is my test environment:
Build tool: DUB version 1.3.0
Compiler : DMD32 D Compiler v2.074.0
OS: Windows 10, Ubuntu
Build type: unittest

Test code:
```D
import std.stdio;

void main()
{
	writeln("Edit source/app.d to start your project.");
}

unittest
{
	assert(false, "It doesn't work.");
}
```

**Comment by dhasenan** [comment]
I've encountered that problem too.

dub currently needs to supply its own entry point so it can run the unittests and not your entire application. So it doesn't compile `source/app.d` and does compile everything else, along with its own generated `main()` function specific to testing.

Dub *could* provide its own test runner. It currently has special handling for the `tested` library, which appears to be going on four years since the last release.

There are a few test runners floating around, so it might make sense to give them a standard way to hook into dub. But that's beyond the scope of this. The simplest way of making things work is to provide a simple, in-line test runner that takes place in the static constructor, then exits before `main` can be called.

**Comment by s-ludwig** [comment]
> There are a few test runners floating around, so it might make sense to give them a standard way to hook into dub.

Definitely makes sense. I think unit-threaded can already hook in, but not sure whether that is using `moduleUnitTester` or some other means. But what would be nice in any case would be to let external test runners have access to the module list, so that they can work without further setup within user code. The easiest way would of course be to let them `import dub_test_root;`.

**Comment by MartinNowak** [comment]
There is a similar needs to get the package version from dub, importing some dub provided metadata module would definitely make sense. Could be a header-only module that doesn't get linked.

Similarly the unittest-runner isn't the first extension point people want to customize, e.g. project generators, ddox tool, build tool. Thoughts welcome.

**Comment by JesseKPhillips** [comment]
It might make sense to output a warning if "unittest" is found in the app.d file. This can let people know of this issue and inform them their tests aren't being executed.

**Comment by ohdatboi** [comment]
Works just fine with dub 1.10.0.
