### ISSUE TITLE
Execute shebang without writing the .d extension

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1124]
Please enhance this logic
https://github.com/dlang/dub/blob/master/source/dub/commandline.d#L102

It should be possible to execute dub without adding the .d extension.
Example: Instead of writing `dub app.d` I want to write `dub app`

Please also notice this thread. Under linux there might be a case where the D source files do not have the
D extension (s.th. with symlink, but as Windows user I do not know the details)
https://forum.dlang.org/post/o5uero$46u$3@digitalmars.com
Therefore dub app should also work if the source file does not have the .d extension

**Comment by jmdavis** [comment]
I would point out that dmd itself requires that D files end with the .d extension, so really, dmd would need to be fixed for dub to do this. It's been brought up before that required the .d extension is not ideal for scripting, but IIRC, Walter was not at all convinced, though I can't find any related enhancement requests in dmd's bugzilla at the moment. Regardless, this is ultimately a dmd issue.

**Comment by jmdavis** [comment]
Oh, so you want the extension to still be .d but for dub to accept the resulting program name as the argument instead of requiring that it be the file name? Well, that could probably be done and would be up to the dub folks, but the issue's description talks about source files not having the .d file extension, and as I understand it, that's illegal. dmd requires that they have the .d extension. And as long as that's the case, dub isn't going to support D source files that don't have the .d extension.

**Comment by andre2007** [comment]
Yes exactly, it is just a convenience feature for the dub call.

**Comment by andre2007** [comment]
Pull request https://github.com/dlang/dub/pull/1605

**Comment by andre2007** [comment]
Solved
