### ISSUE TITLE
sourceLibrary dependencies unittest should not be builded

### ISSUE THREAD

**Issue by 9il** [dlang/dub#1140]

**Comment by MartinNowak** [comment]
Why? Mixing code with `-unittest` and without `-unittest` can easily lead to linker errors atm., b/c the user of an API sees different code from the library.

**Comment by 9il** [comment]
Yes. Then we need to introduce a special flag that make compiler ignore unittest bodies in unittest mode. The reasons:

1. Compiling dependencies unittest bodies slowdown compilation.
2. Running dependencies unittest bodies slowdown the testing.

mir-algorithm is large a large generic source library. It does not contain any code that should be compiled except module information for asserts. It do not have exceptions. It is really painful to test packages that use mir-algorithm.

**Comment by MartinNowak** [comment]
Doesn't seem possible with the current D frontend, see [Issue 14894 – mangling of mixins and lambdas is not unique and depends on compilation flags](https://issues.dlang.org/show_bug.cgi?id=14894).
We could just do it in dub and hope we get away without too many linker errors.

**Comment by joseph-wakeling-frequenz** [comment]
In general it would seem to be a good thing that upstream unittests are built as part of a downstream project (e.g. if I'm building an app, I would like to verify ALL the code that goes into it), so this concern seems to be a bit specific to your use-case.

It would perhaps be better to provide a way to specify to DUB to exclude unittests from certain dependencies, rather than not running them by default.

**Comment by andre2007** [comment]
@9il I would close this issue, please use targetType ```library``` to avoid this issue. sourceLibrary will cause the d modules just to be passed to DMD.

Do you have a reason to use ```sourceLibrary``` ?
