### ISSUE TITLE
copyFiles do not uses platform attribute

### ISSUE THREAD

**Issue by o3o** [dlang/dub#1145]
Hi,
I've this library [dub files](https://github.com/o3o/dinodave)
```sdl
name "dinodave"
targetType "library"
...
libs "nodave" platform="posix"
copyFiles "lib/libnodave.dll" platform="windows" //<---- !!!
...
```
I use this library into [executable project](https://github.com/o3o/dinodave/blob/master/examples/integer/dub.sdl) with this dub file:
```sdl
name "integer"
description "dinodave integer read/write example"
dependency "dinodave" path="../../"
```

So, when I build it in posix platform:
```sh
$ cd examples/integer
$ dub build
Performing "debug" build using dmd for x86_64.
dinodave 0.2.0: target for configuration "library" is up to date.
integer ~master: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Copying files for dinodave...
```
dub copies "lib/libnodave.dll":
```sh
$ ls *.dll
libnodave.dll
```

My environment:
```
$ dub --version
DUB version 1.3.0, built on May 23 2017
$ uname --all
Linux abe 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux
```

Thank you

**Comment by MartinNowak** [comment]
Tested with https://github.com/o3o/dinodave/commit/319063bbe3a4ebe2b78f3eafbc49956444ae4602 and dub 1.3.0, not reproducible.
If you look at your output, you can see that the example builds `dinodave 0.2.0` which unconditionally copies the dll (see [here](https://github.com/o3o/dinodave/blob/759e6f612fa4b116b77a9a32e472d1cbe4cdd773/dub.json#L11)).
Check your dub.selections.json which likely selects `"dinodave": "0.2.0"` instead of `"dinodave": {"path":"../../"}`.

**Comment by o3o** [comment]
Thank you for your reply.
I've tested again and actually now it works.
I apologise for the inconvenience...
