### ISSUE TITLE
std.json cannot parse dub.json

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1205]
std.json is not able to read several dub.json files as they are using
trailing commas.
While the dub implementation of JSON allows trailing commas,
phobos implementation forbidds it (according to JSON spec).

See also here https://issues.dlang.org/show_bug.cgi?id=17693

**Comment by s-ludwig** [comment]
Duplicate of #415 - makes sense to fix this sooner rather than later.

**Comment by Geod24** [comment]
According to the original title, this can be closed because this was merged to Phobos: https://github.com/dlang/phobos/pull/7074

Now regarding making DUB more strict, I don't think it's a good idea. We should never emit trailing commas, but accepting them is IMO better per the robustness principle.

**Comment by andre2007** [comment]
@Geod24 i agree, thanks for looking through the issue list.
