### ISSUE TITLE
module cannot be read

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1218]
Extract the zip archive and execute
dub add-local delta-lib
dub app.d

Error is thrown:
app.d(6,8): Error: module Layouts is in file 'FMX\Layouts.d' which cannot be read
import path[0] = delta-lib\source
import path[1] = C:\D\dmd2\windows\bin\..\..\src\phobos
import path[2] = C:\D\dmd2\windows\bin\..\..\src\druntime\import
dmd failed with exit code 1.

[demo.zip](https://github.com/dlang/dub/files/1220072/demo.zip)

I think this is a false positive and it should compile

**Comment by todayman** [comment]
I'm not convinced that this should compile.
The filesystem path to a module needs to match the package-module name.  That is, the module FMX.Layout should be in FMX/Layout.d.  In the zip file you attached, the module is in the file delphi/fmx/FMX.Layouts.d.
Does that help?

**Comment by s-ludwig** [comment]
Yes, so as long as the "FMX.Layouts.d" is compiled together with everything else, the module statement would make this work, but as soon as it is not on the same compiler command line, like in case of "dub app.d", it will fail because it doesn't know where to find the module. "dub --combined --single app.d" should work again, as would declaring "delta-lib" `"targetType": "sourceLibrary"`, but the only robust solution is to match path with module name.

**Comment by andre2007** [comment]
Thanks, I will close this issue.
