### ISSUE TITLE
Unittest test/interactive-remove-sh fails because of wrong order

### ISSUE THREAD

**Issue by ThomasMader** [dlang/dub#1224]
### System information
dub 1.4.1
Fedora 22
dmd-2.075.1

### Bug Description
The problem is that on some systems the order of the directories listed via dirEntries is different than expected by the unittest.

### How to reproduce?
To reproduce the problem the following program can be used.

```
import std.stdio;
import std.file;
import std.process;
void main()
{
        std.process.executeShell("mkdir dub-0.9.20");
        std.process.executeShell("mkdir dub-0.9.21");
        foreach( DirEntry ent; dirEntries(".", SpanMode.shallow) ) {
                writeln(ent);
        }
}

```

Running it on Mac OSX 10.11.6 gives the correct order for the dub directories:
dub-0.9.20
dub-0.9.21

But on my Fedora 22 machine it is reversed:
dub-0.9.21
dub-0.9.20

Not sure if it should be expected from dirEntries to have the same order in every case so I opened a dub issue instead of a phobos issue for now.

**Comment by s-ludwig** [comment]
Since it makes sense to always have the list sorted from a user's POV, too, I've opened a PR that simply manually sorts the list before printing it out (#1225).

(I'd also agree that DUB is the right place for the fix, as it would be rather inefficient to require `dirEntries` to output the entries in a particular order due to the extra dynamically allocated array of all directory entries that would be required for sorting)
