### ISSUE TITLE
Passing the targetFilePath as console argument to dub

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1271]
For a build infrastructure based on XMake I creating a DLang XMake plugin. The script calls dub to create the binary and the resulting binary has to be included into a archive file. Therefore I need the filepath of the resulting binary.

XMake plugins for other development languages solve this problem by passing the file path of the resulting binary into the compiler/package manager. That feature is currently not existing for dub.
The only possibility is to specify the filepath in dub.json. But the XMake build infrastructure is not allowed to adapt any source code...

My workaround is to call dub describe and to parse the JSON for the attributes targetPath/targetName of the root package. It is working but it is rather cumbersome.

It would be nice if dub can be enhanced to pass targetPath/targetName as console arguments

**Comment by MartinNowak** [comment]
Binaries might rely on resource/source files relative to the binary, so that would easily break with a different targetPath.

> It is working but it is rather cumbersome.

Shouldn't be much of a problem, either use `jq` to get the json field or just `dub describe --data=target-path --data-list`. Not sure there is currently a way to find possible resource files, but by convention you should likely include folders named public for example.
