### ISSUE TITLE
arch attribute in dub.json/dub.sdl

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1327]
At the moment you can specify architecture only as console argument and not as attribute in the dub package file.

I created a CI XMake build plugin for D and every property which cannot be specified within dub.json I have to create a XMake property. Instead of creating an XMake property DUB_ARCH it would be nice if you can add the arch attribute to the dub package file.

**Comment by ohdatboi** [comment]
It's not in dub.json because of the same reason `--compiler` isn't there: dub uses default architecture and compiler by default and there is `--arch` and `--compiler` to override that behaviour.

This is a nice thing because it doesn't allow programmers to tie their packages to a specific architecture/compiler. D is a cross-platform language and most of the times programs work on any machine.

**Comment by andre2007** [comment]
I write Windows applications which targets x86_64 architecture for various reasons. For one applications some DLLs are only available for x86_64. In another application x86_64 solves memory issues. Current work around is to write in the README.MD for my colleagues that you have to add the dub compiler argument for x86_64. Not beeing able to define that these dub projects only makes sense with x86_64 is an artificial limitation for me. Also beeing able to define for several dub configurations individual architectures seems quite reasonable for me.

**Comment by ohdatboi** [comment]
It's not much of dub's fault for not having such feature but dmd's fault for choosing x86 by default on windows. I suggest focusing on fixing dmd instead of adding another not-quite-wanted feature which will become obsolete when dmd is finally fixed.

I think there was some progress in dmd on windows, so hopefully we'll get that fixed soon.

**Comment by ZombineDev** [comment]
There's nothing to fix on dmd's end as one may provide a package with inline assembly only for AArch64 - that's a totally valid use case. Dub should infer that the root package having such dependency is buildable only if it also is compiled for AArch64.

**Comment by andre2007** [comment]
I want to exclude the discussion on DMD chosen X86 as default on windows. It is one possible use case for the arch attribute. There are a lot more use cases.

While you are totally correct, that DMD is cross platform and works on different machines, my opinion is, the developer should have the possibility to either limit on which architecture a project could run or even provide for different architectures different dub configurations. The reason could be that there are different dlls to be used for different architectures or ...

```
{
	...
	"name": "somepackage",
	"configurations": [
		{
			"name": "metro-app",
			"targetType": "executable",
			"platforms": ["windows"],
			"versions": ["MetroApp"],
			"libs": ["d3d11"],
                        "arch": "x86"
		},
		{
			"name": "desktop-app",
			"targetType": "executable",
			"platforms": ["windows"],
			"versions": ["DesktopApp"],
			"libs": ["d3d9"],
                        "arch": "x86_64"
		},
````

**Comment by ZombineDev** [comment]
@andre2007 There's no need for a separate arch attribute, because the platform attribute already allows specifying the arch:

```json
{
	...
	"name": "somepackage",
	"configurations": [
		{
			"name": "metro-app",
			"targetType": "executable",
			"platforms": ["windows-x86"],
			"versions": ["MetroApp"],
			"libs": ["d3d11"]
		},
		{
			"name": "desktop-app",
			"targetType": "executable",
			"platforms": ["windows-x86_64"],
			"versions": ["DesktopApp"],
			"libs": ["d3d9"]
		}
}

**Comment by ZombineDev** [comment]
See also: https://github.com/dlang/dub/pull/1541#issuecomment-417252200

**Comment by andre2007** [comment]
The platforms attribute is the opposite what I had in mind. Platforms works as filter. 
What I had in mind:

- I execute just the command "dub" and as arch is set to x86_64, the whole project is compiler as 64 bit architecture

- I execute "dub -c myconf" and the arch set in configuration "myconf" is used.

**Comment by s-ludwig** [comment]
I think we can achive much of the same effect by changing the way the default configuration and default architecture are chosen. Basically, specifying `--arch` would automatically attempt to select the first matching configuration instead of simply the first one, and similarly, specifying `--config` would default to the first available architecture of that configuration (unless the system default architecture already matches). The same could be done with the compiler.

**Comment by ZombineDev** [comment]
@s-ludwig Exactly what I had in mind. I'm planing to work on adding full target triple support in the context of #228 and https://github.com/dlang/dub/pull/1541#issuecomment-417252200. If I get around to doing that I hope to work on this (top-down and bottom-up platform inference) next.

**Comment by andre2007** [comment]
Solved by https://github.com/dlang/dub/pull/1740
