### ISSUE TITLE
dub respository access specification

### ISSUE THREAD

**Issue by andre2007** [dlang/dub#1349]
Bigger companies won't install dozens of different repositories (npm, gem, docker, yum, ...) but they will use software like [Nexus repository manager](https://help.sonatype.com/display/NXRM3/Supported+Formats) or [JFrog Artifactory](https://jfrog.com/integrations/)

If they decided to also include dub into their list of supported repository they need to know how dub works from an repository access view. What http interface does dub console client expect and so on.
Maybe you can add a page in the wiki which will describe the information they need.

**Comment by MartinNowak** [comment]
Big Corp™ sure would have some time to read a bit of code, instead of peeving unpaid open source workers to preprocess information for them ;). Also wikis are notoriously out of sync.
The API is really small, basically just
https://github.com/dlang/dub-registry/blob/fe18df23b32f602a7579816a801a8a4e98346b5c/source/dubregistry/web.d#L142-L228. We've also started to add a REST API to dub-registry
https://github.com/dlang/dub-registry/blob/fe18df23b32f602a7579816a801a8a4e98346b5c/source/dubregistry/api.d.
You can easily host your own instance of dub-registry for in-house usages.

**Comment by andre2007** [comment]
Thanks for the info. I am not sure whether these commercial companies will look into the source code because dub registry is under GPL license. Maybe you can check whether dub registry could change the license?

**Comment by wilzbach** [comment]
Huh? I didn't know it was released under GPL. 

https://github.com/dlang/dub-registry/pull/272

Looks like it was more or less "accidentally" added in another commit:

https://github.com/dlang/dub-registry/commit/cc08b3509c3107f1d563b69db3d33c0695b35475
