### ISSUE TITLE
allow `dub run -- prog arg1 arg2`

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#1362]
we can do `dub run prog -- arg1 arg2` but it's less natural than `dub run -- prog arg1 arg2` (especially when pasting from a normal cmd `prog arg1 arg2` where we need to insert `--`)

lldb got this right compared to gdb, this is exactly the same situation

**Comment by grogancolin** [comment]
I'm not so sure. To me, everything after the `--` means "Pass these to the thing I'm running". 

Everything before is being passed to `dub run`. The current situation feels natural to me as other commands like `xargs` or `ssh` do for example.

**Comment by s-ludwig** [comment]
A problem with this syntax is that it is ambiguous when dub is run from a package directory. It could default to the old syntax in that case as to not change/break existing usages, but still it could be pretty surprising.

I don't deny that the syntax has its merit, but the analogy to lldb is only half-true, because "prog" in our case is not really the name of an executable, but the name of a package, which may or may not be the same. It gets obvious, especially when sub packages are used: `dub -- foo:bar arg1 arg2` - having a dub specific argument here after the "--" looks rather alien to me.

**Comment by timotheecour** [comment]
looks like https://github.com/dlang/dub/issues/1362 is also going towards `dmd options... -run -- arg1 arg2` so there'd be consistency with that; closing
