### ISSUE TITLE
dub registry request randomly fails

### ISSUE THREAD

**Issue by Extrawurst** [dlang/dub#1425]
### System information
- dub 1.3.0 and up
- Ubuntu 14.04.5 LTS
- v2.076.1 and up

### Bug Description
```
$ dub test --compiler=$DC || exit 1
Package derelict-util not found in registry at http://code.dlang.org/: HTTP request returned status code 502 (Bad Gateway)
```

### How to reproduce?
randomly happens, but now that I have a lot of travis-ci jobs running daily it happens min. once a night.

### Expected Behavior
It should just work. Restarting that job and giving it another spin usually fixes the issue. Maybe a retry mechanism should be considered if the reliability of the registry cannot be improved?

### Logs
```
$ dub --help | tail -n 1
DUB version 1.5.0, built on Oct  9 2017
$ dub test --compiler=$DC || exit 1
Package derelict-util not found in registry at http://code.dlang.org/: HTTP request returned status code 502 (Bad Gateway)
Root package derelict-fmod references unknown package derelict-util
```
referenced project: https://github.com/Extrawurst/DerelictFmod but the problem applies to all projects handling dependencies with `dub`

**Comment by wilzbach** [comment]
> It should just work.

Yes.
FYI: The dub-registry is currently experiencing some issues with high memory usage / memory leaks and @s-ludwig is actively working on this.
The last post on #dub (in the D Slack) a couple of hours ago:

> So I've gone through the code and identified a number of places that are responsible for high memory usage (not all fixes committed yet). Unfortunately a (the?) major leak is happening in the low-level  MongoDB query code, which has no "obvious logical cause", so my suspicion is that this is caused by false pointers or by a low level GC related problem (maybe fiber related). I'll do some more research tomorrow. The good news is that at least the memory usage growth rate can be reduced enough that the current situation can be relaxed again.


> Maybe a retry mechanism should be considered if the reliability of the registry cannot be improved?

FYI: dub 1.5.0 doesn't come with backup mirror nor retry logic. That's included in 1.6 and 1.7.2 comes with more mirror and retry logic.

Since a few months the installer doesn't update the dub binary anymore (if one is included), but uses the bundled one.
There's a PR to allow e.g. `dmd-2.076.0+dub` which instructs the install script to download the newest version of dub, but it's pending in the PR limbo for a while now, because the only person who can deploy this (Martin) is currently very busy.

https://github.com/dlang/installer/pull/301

There's also https://github.com/dlang/installer/pull/273 to use a fallback mirror for code.dlang.org when the dub binary needs to be download, e.g. the case for dmd < 2.072, < ldc 1.2.0 and gdc)

**Comment by Extrawurst** [comment]
@wilzbach wow thanks for the info. Interesting to hear that there is a slack channel. i cannot for the live of me find a link on the official dlang.org page to it? nor can i google for it, or is it: `https://dlang.slack.com/` ? If so it just tells me to contact the admin to get access - wtf ^^

**Comment by wilzbach** [comment]
I'm not an admin, but every user can invite other and I just did so.

> nor can i google for it, or is it: https://dlang.slack.com/ ? 

Yeah it's semi-private at the moment as it's really useful, but it has a few severe downsides that prevented us from announcing it publicly: doesn't satisfy the hard-code IRC users (and slack is about to terminate their bridge) + the non-profit version is capped to 250 users.

**Comment by s-ludwig** [comment]
Should indeed be solved, I haven't experienced a similar issue in the recent months now.
