### ISSUE TITLE
failing dependency resolution

### ISSUE THREAD

**Issue by gedaiu** [dlang/dub#1442]
### System information

- **dub version**:  dub 1.8.0
- **OS Platform and distribution**: linux
- **compiler version**:  dmd 2.079.0

### Bug Description
Dub can not match a patch version. 
Dependency libdparse -> stdx-allocator 2.77.0 mismatches with selected version 2.77.1 (ci=19)

### How to reproduce?
I'm not sure, sometimes it works

### Expected Behavior
I am expecting that dub accepts the patch version since there should not be any api changes

### Logs
https://circleci.com/gh/gedaiu/trial/72
[out2.txt](https://github.com/dlang/dub/files/1887630/out2.txt)

**Comment by Geod24** [comment]
Are you still seeing this ? Without a clear way to reproduce, it's hard to tell if this issue is still relevant.
There have been a large overhaul in the dependency resolution process since that issue was opened and the message you are seeing is a typical symptom of the old problem the overhaul fixed.

**Comment by gedaiu** [comment]
I think we can close this one if I have problems with those packages in the future, I will open a new issue.
