### ISSUE TITLE
Default to x86_mscoff or x64 on Windows

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#1465]
Apparently there are tons of issues with OPTLINK, e.g.

https://forum.dlang.org/post/abxmmjwpwmelxyicuzip@forum.dlang.org
https://issues.dlang.org/show_bug.cgi?id=18799
https://issues.dlang.org/show_bug.cgi?id=17508

Maybe it's a good idea to use x86_mscoff or even better x64 as default architecture on Windows.

**Comment by andre2007** [comment]
On Windows this will force the user to install Build Tools from Microsoft because the MS linker is needed. Dmd now also ships with the linker from llvm to avoid the download of the Build Tools but I am not sure how mature that solution is.In dub settings.json it is already possible to set the default architecture.  In the project specific dub.json the option to set the architecture is missing.

**Comment by andre2007** [comment]
In the meantime DMD and LDC comes with x86_64 linker and MinGW-w64-based libraries. Seems reasonable to switch to x86_64 as default on Windows.

**Comment by thewilsonator** [comment]
For 64-bit sure. Do we have 32-bit lld and libs yet?

**Comment by thewilsonator** [comment]
Thanks for that.

**Comment by andre2007** [comment]
Implemented by @wilzbach

**Comment by Geod24** [comment]
Fixed by https://github.com/dlang/dub/pull/1661 which is part of v1.15.0
