### ISSUE TITLE
Wrong line number reported in exception information

### ISSUE THREAD

**Issue by TransientResponse** [dlang/dub#1689]
### System information

- **dub version**: 1.14.0
- **OS Platform and distribution**: Windows 10 1809 x64
- **compiler version**: 2.085.1

### Bug Description
When running a dub project with `std.algorithm.copy` into a too-short slice, the error is reported on the next line after where the actual assert came from. 

### How to reproduce?
Put this into a new simple dub project:
```d
import std.stdio;
import std.datetime;
import std.base64;
import std.string;
import std.algorithm;

private immutable string[] months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

void main()
{
    DateTime dateProgrammed = DateTime(2019, 4, 24);
    
    ubyte[] full = new ubyte[128];
    copy("test_string".representation, full[8..16]);
    
    import std.format: format;
    string date = format!("%d-%3s-%d %02d:%02d")(dateProgrammed.day, 
        months[dateProgrammed.month-1], dateProgrammed.year, 
    dateProgrammed.hour, dateProgrammed.minute);
    copy(date.representation, full[24..44]);
    
    Base64.encode(full).writeln;
}
```

`dub build` and execute or `dub run`

### Expected Behavior
Error of something like
```
core.exception.AssertError@C:\D\dmd2\windows\bin\..\..\src\phobos\std\algorithm\mutation.d(373): Cannot copy a source range into a smaller target range.
----------------
0x0040EEBD in _d_assert_msg
0x004022EA in _Dmain at <snip>\test_dub_error\source\app.d(14)
```

Rather than the line 17 as currently reported

**Comment by WebFreak001** [comment]
This isn't a dub issue but rather an issue with the debug info generation in dmd/ldc. Try if it works fine in LDC. Line numbers just sometimes move around a bit in long stack traces especially in my experience.

Dub is (roughly speaking) just for fetching dependencies and invoking the compilers to build your program. Dub never outputs anything like this error and also it's an exception message of your program at runtime instead of some compiler error or anything like that.

There have been bug reports about this before but idk if you can really find your cause on the issue tracker that easily. It might be worth a shot posting it on there, however I can't reproduce your issue there on my linux machine, so maybe check on some other systems if it happens too.

**Comment by TransientResponse** [comment]
You are correct, this isn't a dub issue. I had tricked myself into thinking this issue wasn't appearing outside dub builds but adding the debug flag makes it appear. 

My apologies for the false report, I can now confirm this is only happening on Windows with DMD, and not with LDC or DMD on my Fedora VM.
