### ISSUE TITLE
docs says toolchainRequirements' values can be "no", but causes issue for dependent projects

### ISSUE THREAD

**Issue by skoppe** [dlang/dub#1752]
in `spasm:0.2.0-beta.1` I use `toolchainRequirements dmd="no" gdc="no" ldc=">=1.15.0"`, which works great for local development, but when I create a project that depends on it it gives me errors about invalid SemVer after downloading the spasm package.

When I look into the downloaded `.dub/packages/spasm` folder I see a `dub.json` where the values of the toolchainRequirements say `invalid` instead of the `no` I wrote earlier.

Is `no` a valid value?

**Comment by Geod24** [comment]
From what I just tried, it is. Perhaps the registry doesn't handle it ?

**Comment by skoppe** [comment]
Yes, it is the only one that mucks with the sdl/json files.

**Comment by s-ludwig** [comment]
From a quick look, both, `PackageRecipe.toSDL` and `toJson` are partially broken w.r.t. `ToolchainRequirements`, which means that `dub convert` is also broken, in addition to the registry.

`toSDL` should use `.versionSpec` instead of `toString`, which is not meant to provide machine readable output. Both, `toSDL` and `toJson`, have to check for `Dependency.value` and output "no" in that case, because right now, the result will be "invalid" instead, which in turn cannot be parsed.
