### ISSUE TITLE
It should be possible to build the test target and not run it

### ISSUE THREAD

**Issue by AndrejMitrovic** [dlang/dub#1856]
During development it makes sense to frequently compile the codebase without running the compiled binary. However `dub build` does not build the test target, `dub test` does. But `dub test` also runs the test binary.

I want the ability to compile the `test` target without running it.

**Comment by Geod24** [comment]
What about `dub build -b unittest` ?

**Comment by AndrejMitrovic** [comment]
Hmm.. that gives me a linker error.

**Comment by AndrejMitrovic** [comment]
(in our project)

**Comment by Geod24** [comment]
Looks like `dub build -c unittest -b unittest` works. We should look into it, but I think `-b unittest` should imply `-c unittest`. Although those day I think `-b` and `-c` are just redundant.

**Comment by foerdi** [comment]
Unfortunately this only works if `targetType` is "executable" or your project has a separate unittest configuration.
In a simple library project without a custom unittest configuration, Dub build a library instead of an executable.

**Comment by HuskyNator** [comment]
I have this very same issue. The issue is essentially the inability to build the unittest build for libraries. In my scenario `dub test` is not an option, so this would be required.

As a temporary workaround one can either:
1. Add a versions argument that causes the inclusion of a main.
2. Add a sourceFiles argument that includes a file with a main.

In both of these workarounds one should also add `"targetType":"executable"`.

In the scenario in which no previous configuration existed in the project, one is however _also_ required to add an empty configuration, purely to prevent the automatic use of this test configuration (this seems like a code-smell to me).

Example:
```
"configurations": [
  {
	  "name": "default",
	  "targetType": "autodetect"
  },
  {
	  "name": "unittest",
	  "targetType": "executable",
	  "sourceFiles": [
		  "test/emptyMain.d"
	  ]
  }
]
```

**Comment by WebFreak001** [comment]
I would be for moving the special cases out of `dub test` into `dub build -c unittest`

potential improvements:
- easier to understand
- easier to build unittests as part of the dub API (for IDEs)
- one less section where the target path (with suffix etc) is being generated
  - `dub describe` could actually report the unittest executable path when querying the output path
