### ISSUE TITLE
404: package caching issue?

### ISSUE THREAD

**Issue by mingwugmail** [dlang/dub#1968]
Fetching d-profile-viewer 1.1.3 (getting selected version)...
Downloading https://code.dlang.org/packages/d-profile-viewer/1.1.3.zip failed with 404 (Not Found).
Makefile:18: recipe for target 'build' failed

**Comment by andre2007** [comment]
I am not used to BitBucket but it seems the tag 1.1.3 does not exist. Maybe the author has deleted it?

I do not know wheter Dub Registry has a self healing in case tags are deleted (an action you should not do).

The issue is created in wrong repository. The dub repository is about the dub client, not the Dub Registry.

**Comment by mingwugmail** [comment]
ok, filed issue there.

closing this one.
