### ISSUE TITLE
cannot build profdump: Enforcement failed

### ISSUE THREAD

**Issue by mingwugmail** [dlang/dub#2017]
I remember I used to able to build this package:

https://github.com/AntonMeep/profdump

but now, I cannot.

https://github.com/AntonMeep/profdump/issues/6

Since that package haven't changed for 2 years, maybe it's a dub bug?

### System information
```
$ uname -a
Linux  4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ /usr/bin/dub --version
DUB version 1.23.0, built on Sep 27 2020

$ /usr/bin/dmd --version
DMD64 D Compiler v2.094.0
Copyright (C) 1999-2020 by The D Language Foundation, All Rights Reserved written by Walter Bright

$  /usr/bin/dub build -v
Using dub registry url 'https://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
...
...
No valid package found in current working directory: Enforcement failed
Enforcement failed
```

### Bug Description
Enforcement failed

### How to reproduce?
```
git clone https://github.com/AntonMeep/profdump

cd profdump

dub build

```

**Comment by drug007** [comment]
As I can see the configuration file is incorrect or dub has changed it behaviour. If you add targetType "executable" to subconfiguration "executable" and remove subconfiguration "unittest" then the project builds as expected. I guess that dub fails due to the missing version of "fluent-assert"
```
			"dependencies": {
				"silly": {"path": "../silly"},
				"fluent-asserts": ""
			}
```
and absent local repository of "silly"

At least if you remove "unittest" subconfiguration and add targetType "executable" to subconfiguration "executable" (or delete of subconfigurations at all) the project builds

**Comment by mingwugmail** [comment]
ok, thanks for the work-around.

https://forum.dlang.org/post/rkveo0$1n6m$1@digitalmars.com

> It reproduces. As a workaround you can use
> ```
> dub run profdump
> ```
> this command works as expected, I guess it is a bug of dub

Do not execute this command in cloned `profdump` repository - it will fail too. It works if is called from other places, for example in home.

**Comment by Geod24** [comment]
Thanks for the investigation @drug007 , closing as invalid.
