### ISSUE TITLE
Cannot compile when there are warning.

### ISSUE THREAD

**Issue by vova616** [dlang/dub#206]
trying to compile this

```
import std.stdio;
void main()
{
    return;
    writeln("Edit source/app.d to start your project.");
}
```

will fail with

```
Compiling...
source\app.d(6): Warning: statement is not reachable
FAIL .dub\build\application-debug-x86-dmd-4605D066D2D747798C43437270C61493 test executable
Error executing command build: DMD compile run failed with exit code 1
```

but this code will compile just fine

```
import std.stdio;
void main()
{
    writeln("Edit source/app.d to start your project.");
}
```

am I missing something?

DMD32 D Compiler v2.064
Windows 7 64bit
fails on dub 9.20/9.21/master branch, it used to work with older versions of dub though.

**Comment by WebFreak001** [comment]
This does not work when a subpackage has warnings. I am currently trying to compile a program in unittest mode with "dub" as dependency and I just can't run unittests because of this error `../../.dub/packages/dub-0.9.24/source/dub/internal/vibecompat/data/utils.d(476,4): Warning: statement is not reachable`

**Comment by s-ludwig** [comment]
I'll have a look and fix the error for dub. I'd say that generally such warning related errors have to be treated like any other issue - it's the responsibility of the package author to fix it. After all, a warning is just one possibility to make the build fail.

As a workaround it may work to specify the `-wi` switch in a custom "unittest" build type within the main project, since the build type settings are applied to all packages in the dependency graph.

**Comment by s-ludwig** [comment]
Okay, turns out this has already been fixed on master.
