### ISSUE TITLE
suggestion: can dub deprecate one format: dub.sdl or dub.json

### ISSUE THREAD

**Issue by mw66** [dlang/dub#2267]
Hi,

I have both dub.sdl and dub.json (for testing different option purpose) in the current dir, looks like `dub build` will pick dub.sdl by default, how can I explicitly choose one of them on the command line?

Thanks.

**Comment by WebFreak001** [comment]
dub should pick the dub.json as priority (see https://github.com/dlang/dub/blob/96d2536620fe110bd03ef2f81afb47e503018e4f/source/dub/package_.d#L46)

Otherwise there is no way to specify which recipe file to pick, see https://github.com/dlang/dub/blob/96d2536620fe110bd03ef2f81afb47e503018e4f/source/dub/package_.d#L152

it would be possible to add some flag to specify an explicit file, but I think it's not a good idea as that flag would be needed on all dependents as well that want to depend on your package. I think having a consistent, no-exceptions, way of having package descriptions is worth more than the flexibility for the weird case where you have more than one package file. If you want to test different options you could create a subfolder / subpackage with your source code and make them reference the same code (change sourcePaths or maybe create a symlink), then you can use `dub build --root=someDirectory` or `dub build --root=otherDirectory` to build the different directories (or use `dub run` or just `dub`)

**Comment by mw66** [comment]
OK, right now, I manually rename one of the file to something dub does not recognize.

**Comment by WebFreak001** [comment]
no, there is too much on the ecosystem now and the decision when SDL was added was in part because of writing experience of JSON. See https://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/thread/2/ for discussions

If you want to make a utility to parse dub.json and dub.sdl, either use dub as a library or call `dub convert -s -f json` to read the recipe if you don't need high performance. You probably want to do it anyway to normalize a few things in the format, which convert does. (remove trailing commas, adjust dependency version syntax)
