### ISSUE TITLE
No way to version local packages.

### ISSUE THREAD

**Issue by ghost** [dlang/dub#267]
There currently is no way to set a version for local packages. 

This means that when you have multiple packages locally, there is no way to have them depend on each other. The dependencies will never be satisfied. 

Question on the forums: http://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/thread/1123/

**Comment by WebFreak001** [comment]
@s-ludwig the rejectedsoftware forum that is linked here seems to be down (or at least that thread doesn't exist), which seems to be important for this issue's context. Can you check if you still have the content for that thread lying around somewhere?

Otherwise as nobody else commented or reacted on this, nor linked to this from other issues, I would suggest closing this as it seems there is either nobody else who really wants this feature or another issue with more description about this has already been opened.

**Comment by WebFreak001** [comment]
closing this since you can specify dependencies per path, per repo+commit and per version now. Sub-packages always share the same version as their package part, but maybe we can lift that restriction in a separate issue if needed. (for DUB 2.0)
