### ISSUE TITLE
Default to any available compiler

### ISSUE THREAD

**Issue by rjpower** [dlang/dub#298]
Apologies if this is a duplicate (I didn't see any identical issues).  I'm new to D and Dub, and was trying to get started with vibe.d on Ubuntu.   After installing GDC, I ran dub and got this error:

```
Running dmd...
FAIL .../libevent-debug-linux.posix-x86_64-dmd-... vibe-d staticLibrary
Error executing command run: Executable file not found: 
```

At first I assumed this was due a missing libevent library -- I didn't notice the `Running dmd...` until later.  Suggestion one is to enhance the error message with something like:

```
Failed to find compiler (dmd)
```

Suggestion two: if `dmd` isn't available, fall back to `gdc` or `ldc`?  I've seen other issues propose preference orders for packages; this is more along the lines of a default compile order; users could change it if they liked.

**Comment by joakim-noah** [comment]
>Suggestion one is to enhance the error message

It now says `Failed to invoke the compiler dmd to determine the build platform: /bin/sh: dmd: not found`.

>if dmd isn't available, fall back to gdc or ldc

[dub now tries](https://github.com/dlang/dub/blob/e6059026504eafe4a12855c26d1dbbf30f4fd84b/source/dub/dub.d#L227) this list: [dmd, gdc, gdmd, ldc2, ldmd2](https://github.com/dlang/dub/blob/e6059026504eafe4a12855c26d1dbbf30f4fd84b/source/dub/dub.d#L1170).

It appears this issue is now fixed.

**Comment by joakim-noah** [comment]
@wilzbach, what do you think?

**Comment by wilzbach** [comment]
Sorry I missed that one.

> @wilzbach, what do you think?

You should receive rights to close issues yourself.
