### ISSUE TITLE
Support non-repo packages

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#50]
Particularly for non-public libs/projects or projects needing a specific alternate fork of a dependency, DUB needs a way to specify a dependency on an arbitrary Git repo URL (Whether local, online, login-protected, etc.)

**Comment by deviator** [comment]
When you plain to implement this? [dlibgit](https://github.com/s-ludwig/dlibgit) written for this issue?

**Comment by s-ludwig** [comment]
There is no fixed date/plan for this, yet. Next priority will be to get C language family build support. But this of course doesn't mean that someone else couldn't create a pull request.

An implementation of this should probably use the command line git tool rather than `dlibgit`, because `libgit` is available in different versions on different Linux distributions and different versions usually have incompatible APIs.

**Comment by dhasenan** [comment]
Another approach to this: add the repo as a git submodule, then add the path to the dependency in dub.json. This has the advantage that you can add different versions in different projects.

**Comment by dhasenan** [comment]
Yet another way to do this, if you have a sufficiently large organization: use a private dub registry. Considering there are at least three ways to accomplish this (`dub add-local`, submodules, private registries), do we need a fourth?

**Comment by wilzbach** [comment]
> Considering there are at least three ways to accomplish this (dub add-local, submodules, private registries), do we need a fourth?

Yeah, "missing git support" is one of the top complaints about dub. Paths and submodules do okayish, but for example, submodules aren't currently fetched by DUB. This while being old, I think this issue is still valid today

**Comment by WebFreak001** [comment]
I think this would be really useful

**Comment by Geod24** [comment]
We now have the ability to depend on an SCM repository directly. We also have path dependencies, so I think that covers it.
