### ISSUE TITLE
Dub doesn't obey versions correctly

### ISSUE THREAD

**Issue by SerialVelocity** [dlang/dub#534]
In my dub.json, I relied on:

``` json
"jsonizer": "~>0.1.0"
```

According to the package format spec, it shouldn't be able to use `0.2.0`. It did though.

Also, I now have:

``` json
"unit-threaded": ">0.4.6 <0.5.0",
```

This is still using version `0.4.6` but should throw an error instead.

**Comment by SerialVelocity** [comment]
Also, ```>0.4.6``` doesn't seem to work and still pulls in 0.4.6.
If I change it to ```>=0.4.7``` it says failed. Isn't a later branch ```~master```?

**Comment by s-ludwig** [comment]
Did you test this with the latest RC of DUB? I've fixed a similar issue recently.

`~master` doesn't match any version (anymore), as there is no guarantee that the master branch is even related to tagged versions.

**Comment by SerialVelocity** [comment]
I haven't. I'm using the latest released version with Mac Homebrew. I'll try upgrading.

Is there a way to say use ```>0.4.6 < 0.5.0``` or fallback to ```~master```? It would be nice to be able to make sure bugfixes are picked up when using CI servers.

**Comment by SerialVelocity** [comment]
Just tested ```>0.4.6 <0.5.0``` and it seems to now through an "invalid package" error now as expected.

The fallback case would be nice to have since I want ```~master``` until ```0.4.7``` is released.

**Comment by s-ludwig** [comment]
There are two main possibilities to use master:
 - manually edit dub.selections.json and put `"~master"` there.
 - check out the git repository locally and add it using `dub add-path` or `dub add-local`. It will then detect the latest tag on that branch and match according to that. This is also a nicer solution, because it will avoid constantly downloading a new ~master zip archive when upgrading (git pull would be used instead).

But generally, to avoid breaking foreign projects, this should only be used for internal development and not for public packages.

**Comment by SerialVelocity** [comment]
So, for local testing I don't have a problem with it. The problem I'm facing is that I can't merge feature branches (which can only be merged once the CI tests pass) because vibe.d has an incompatibility with unit-threaded which causes an infinite loop. The fix has gone into unit-threaded but it is not yet in a released version. This means that my CI is saying build failed after the timeout is reached. It seems like it won't come up in personal projects a lot but will in non-personal projects where CI servers are used to enforce that code doesn't break anything.

**Comment by s-ludwig** [comment]
IMO this is better solved by simply tagging a quick point release of unit-threaded (or at least a `-beta` release). At least you get a reproducible state like that and don't pull in accidental regressions that occur during development.

**Comment by SerialVelocity** [comment]
That works when the project you're pulling in is controlled by you, much harder when it is controlled by someone else. Couldn't this also fix the case where one library works with versions ```0.4.2```-```0.4.8``` and ```0.5.6```-```0.5.9``` and another package is pulling in version ```0.4.6```? It means that the version pulled in satisfies both dependencies which at the moment the pulled in version will most likely be set to ```~>0.5.6```?

**Comment by s-ludwig** [comment]
> That works when the project you're pulling in is controlled by you, much harder when it is controlled by someone else.

But you are already dependent on the external author to fix the issue in the first place. Adding a version tag is really not much more. If the author is not cooperative, a fork would be the last resort.

> Couldn't this also fix the case where one library works with versions 0.4.2-0.4.8 and 0.5.6-0.5.9 and another package is pulling in version 0.4.6? It means that the version pulled in satisfies both dependencies? At the moment, the dependency version of the former will most likely be set to ~>0.5.6.

You mean that a library specifies 0.5.6-0.5.9 as the version range for a dependency and 0.4.1-0.4.8 as a fallback? I don't think that this is necessarily a good idea, it's already difficult/involved enough to verify that something works with a single version range and testing all matching versions (and combination or versions) on a CI server sounds rather unrealistic.

I mean 0.x.x versions are always special, but once a library switches to regular SemVer, something `~>1.2` would due to the backwards compatibility requirements generally be sufficient to cover a large range of versions, so that version range conflicts between different packages become relatively rare.
