### ISSUE TITLE
Root package foo contains reference to invalid package libdparse

### ISSUE THREAD

**Issue by MartinNowak** [dlang/dub#537]
``` sh
dub init foo libddoc libdparse
cd foo
dub build
```

It seems the culprit here is that the packages lists libdparse with a `0.2.0` dependency, while libddoc requires `~master`.

**Comment by MartinNowak** [comment]
A workaround is to require `"libdparse": "~master"` in `foo` itself.

**Comment by MartinNowak** [comment]
The problem is somewhere [here](https://github.com/D-Programming-Language/dub/blob/7ab1881b67168b2bd0813f70840f2005c578f803/source/dub/dependencyresolver.d#L92 w) where the 0.2.0 configuration get's filtered out for some reason.
We need to improve our terminology, because that code reads like nonsense with all those `root`, `parent`, `config`, `package`, `basepack`, `getSpecificConfigs`, `findConfigsRec`.

**Comment by s-ludwig** [comment]
These should be fine:
 - "root package": The package that forms the root of the dependency graph, i.e. the one that gets built
 - "parent package": A package that is a direct predecessor in the dependency tree - there can be more than one
 - "configuration": A "configuration" as documented in the package format spec
 - "package": ...
 - "base package": When sub packages are involved, the package that contains all sub packages

These are not ideal:
- `getSpecificConfigs`: Since this is part of the generic `DependencyResolver`, "config" can mean anything here, for example a "version". A different word would be good to have here.
- `findConfigsRec`: This code should be replaced by an invocation of the `DependencyResolver` anyway. Otherwise it just means to find a valid set of "configurations" (as in the package spec) for a dependency graph.

**Comment by MartinNowak** [comment]
> getSpecificConfigs: Since this is part of the generic DependencyResolver, "config" can mean anything here, for example a "version". A different word would be good to have here.

Sounds like that's the actual `resolveConfigs` step.

**Comment by Geod24** [comment]
More on this:
I just rebased https://github.com/economicmodeling/harbored/pull/22 and tried to build.

You get the following message:
````
Error executing command run:
Sub package libdparse: doesn't exist.
````

There's 3 issues here:
- The message is horribly misleading. Unless I'm mistaken, the "doesn't exists" comes from libddoc requiring libdparse, not the root package itself, but the user has no way of knowing, until he runs it in verbose mode.
- Obviously, I ask for the same version of `libdparse` in `libddoc` and `harbored`, so it should 'just work';
- This is a regression, since 0.9.22 works just fine (and ironically, I put that very line of code in the cookbook..).

Verbose output:
````
2 geod24@barsoom2 /mnt/shared/projects/harbored (git)-[dub-support] % ../dlang/dub/bin/dub -v                :(
Using dub registry url 'http://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/geod24/.dub/packages/local-packages.json
Try to load local package map at /home/geod24/.dub/packages/local-packages.json
Note: Failed to determine version of package mylib at .. Assuming ~master.
Determined package version using GIT: harbored ~dub-support
Refreshing local packages (refresh existing: false)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/geod24/.dub/packages/local-packages.json
Try to load local package map at /home/geod24/.dub/packages/local-packages.json
Adding local /mnt/shared/projects/harbored/libdparse
Note: Failed to determine version of package libdparse at .. Assuming ~master.
Found dependency libdparse >=0.0.0 @./libdparse
Adding local /mnt/shared/projects/harbored/libddoc
Note: Failed to determine version of package libddoc at .. Assuming ~master.
Found dependency libddoc >=0.0.0 @./libddoc
Error executing command run:
Sub package libdparse: doesn't exist.
````

**Comment by MartinNowak** [comment]
Hasn't this been fixed in the meantime?

**Comment by MartinNowak** [comment]
> Hasn't this been fixed in the meantime?

Nope, apparently still a problem.

**Comment by 9il** [comment]
+1

**Comment by WebFreak001** [comment]
dependency resolution errors have been improved, this should no longer occur.
