### ISSUE TITLE
Dynamic/shared libraries as dependencies

### ISSUE THREAD

**Issue by semimono** [dlang/dub#571]
I looked for a bit and didn't find any issue for this.  When a dependency (in my case, a subpackage) has a targetType of dynamicLibrary, dub gives the error message "Dynamic libraries are not yet supported as dependencies - building as static library."  Is there any blocker to this feature being implemented other than time?  How high is it on the priorities list?

In my case I would need some of the dependencies getting placed in bin along with the root package's executable, but some would need to be placed into an alternative path (at least on Unix), so I would need full manual control over where each package is placed (via targetPath or some such property).  Then I would add something to the rpath of the root package for Linux and use the painful SetDllDirectory functionality in Windows (not an issue with dub).

**Comment by JakobOvrum** [comment]
There's another problem when dependencies end up like so:
```
  Program
  /     \           <--- runtime link
libx.so liby.so
  \     /           <--- static link
   libz.a           (contains a D module 'z')
```
If libx, liby and libz are D programs, then you'll get an error like this:
```
Fatal Error while loading 'liby.so':
	The module 'z' is already defined in 'libx.so'.
```
Presumably the intended way to solve this is to link libz dynamically in x and y so that there's at most one instance of module 'z' per process, but this seems impossible with dub.

I could be wrong, but a quick glance at the sources suggests that dub passes dependency libraries as source files on the command line. I tested this with a `.so` to gcc which seems to work in the same way as passing a `.a`. What's the reason dub needs to treat dynamic library dependencies differently? I think this should be orthogonal to the PIC issue.

**Comment by MartinNowak** [comment]
> Presumably the intended way to solve this is to link libz dynamically in x and y so that there's at most one instance of module 'z' per process, but this seems impossible with dub.

My favored approach is to add a `--shared` option to dub build which changes the meaning of the `library` target type from `staticLibrary` to `dynamicLibrary`.
But yes, having static libraries as dependencies of shared libraries is asking for troubles (easy to violate [ODR](https://en.wikipedia.org/wiki/One_Definition_Rule)).

**Comment by nordlow** [comment]
What's reason for this limitation?

**Comment by Geod24** [comment]
No inherent reason I know of besides the lack of someone implementing them.
