### ISSUE TITLE
Allow libs when target is a library

### ISSUE THREAD

**Issue by Temtaime** [dlang/dub#591]
Currently dub ignores all libraries used in project that targets a library.
I think it's wrong because we can pass static libraries to dmd as we pass the object files and those libraries will be merged with objects files resulting in one composite library.

**Comment by Temtaime** [comment]
BTW C++ works in the same way : it allows to pass other libraries when linking a library.

**Comment by s-ludwig** [comment]
Instead of merging it into the library file, it will link it to the final executable or shared library. This is necessary to avoid issues in diamond hierarchies (multiple definition of symbol X).

But, in cases where the developer knows that there will be no issues and where the built static library is supposed to be used outside of the DUB ecosystem, we could add some kind of option to force it being merged.

As a workaround it should work to put the libraries into the "dflags" field.

**Comment by WebFreak001** [comment]
`"libs"` can be used to specify paths to statically built libraries to link in at the end.

`"sourceFiles"` can be used (and has been used) to pass compiled object or archive files into the target.

If there is something I missed here, feel free to reopen.
