### ISSUE TITLE
Build executable dependencies before running pre(Build|Generate)Commands

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#594]
Currently, commands in preBuildCommands and preGenerateCommands cannot safely rely on any of their external tool dependencies without manually doing a `cd [some package dir] && dub build` first. This is because the end user might not have already fetched and built the dependency in question yet.

Since executable dependencies can't participate in "whole project at once" compilation and must be built separately anyway, they should automatically be built _before_ running preBuildCommands and preGenerateCommands. This way they can safely be used with no extra fuss and without the overhead of additional nested invocations of dub.

**Comment by WebFreak001** [comment]
for preGenerateCommands this is by design

preBuildCommands gets run before the build step of the package it self, but after the dependencies have been built. (as libraries)

If you want to run dub dependencies as executables, use `$DUB run packagename` in your preBuildCommands/preGenerateCommands.

It will fetch and run them without them being a dependency. You can also specify a version using `$DUB run packagename@1.0.0`
