### ISSUE TITLE
Convert tests from bash to D so they work on Windows

### ISSUE THREAD

**Issue by Abscissa** [dlang/dub#605]
Just a thought, if the tests are converted from bash to D, it'd be a lot easier to get them working on Windows. If that's acceptable, I'd be willing to do a PR when I get a chance.

**Comment by s-ludwig** [comment]
I'd be very much in favor of that. It would also be good to make it easier to write custom test scripts. Currently a bunch of ".no_*" files have to be added in addition to a test script that is outside of the test's folder. It would be better to search for a "test.sh/d" file in each test directory and then automatically pick that instead of directly building.

**Comment by andre2007** [comment]
It is very easy to run the tests on Windows. With git installation there comes "git bash". Just write 
```
export DUB=c:/path/dub.exe
./test/run-unittest.sh
```

Feel free to reopen this issue if this does not solve your issue.
