### ISSUE TITLE
Dub hangs up while configs validating.

### ISSUE THREAD

**Issue by drug007** [dlang/dub#668]
What is the purpose of this [line](https://github.com/D-Programming-Language/dub/blob/v0.9.24-rc.3/source/dub/dependencyresolver.d#L106):
```
foreach (ref cfgs; all_configs) cfgs = CONFIG.invalid ~ cfgs;
```
This line adds 'invalid' config to all configs and that causes infinite loop while config validation because (I guess) dub is trying to choose a config that matches 'invalid' configs and this is impossible. But I'm not sure. In my case commenting this line let me avoid hanging, moreover hanging has stochastic nature, it's really frustrating. It would be nice if someone help me to get it clearer.

**Comment by drug007** [comment]
Of course I read the comment above this line (just in case). Wouldn't it enough if change it to:
```
foreach (ref cfgs; all_configs) 
    if(!cfgs.length) cfgs = CONFIG.invalid;
```

**Comment by s-ludwig** [comment]
My guess is that this is not an actual infinite loop, but an instance of #652. The "invalid" configuration is there to support cases where a certain package doesn't have a valid configuration available, but the dependency tree is still valid, because the dependency is optional or not required due to an upstream dependency not being included. The resolution algorithm will most probably be reformulated as a graph search algorithm (using a stack/queue), which should get rid of all but the most pathological cases that result in huge resolution times.

**Comment by drug007** [comment]
Yes, I guess you're right, this is a duplicate of #652. But what about adding of "invalid" configuration only if there is no valid configuration like I mentioned above? It's just a guess, I don't know the whole logic behind configuration resolution, but in my case it works very well.

**Comment by MartinNowak** [comment]
Fixed by now.
