### ISSUE TITLE
Support reading package recipe from stdin

### ISSUE THREAD

**Issue by s-ludwig** [dlang/dub#675]
An additional command line switch that takes the format of the package description file could be used to drive DUB from other applications without explicitly writing a package recipe file to disk. See http://forum.rejectedsoftware.com/groups/rejectedsoftware.dub/thread/5591/

**Comment by MartinNowak** [comment]
Somewhat similar to the single file package.

**Comment by MartinNowak** [comment]
Does it need to be a switch? For what other use cases would you send something to dub via stdin?

**Comment by s-ludwig** [comment]
How would you otherwise know if you should wait for input on stdin, or to look for a package recipe file/fail if none is found? It also needs to know the format (JSON/SDL), or at least that feels cleaner than trying both.

**Comment by MartinNowak** [comment]
Just check EOF of stdin after trying to read?

**Comment by s-ludwig** [comment]
But if nothing gets piped to the process, stdin will just sit and wait for keyboard input. There is no EOF in that case. Also that still doesn't solve the format issue.

**Comment by andre2007** [comment]
Dub supports now single package files from stdin.
Does this solve this issue?

**Comment by andre2007** [comment]
Implemented with https://github.com/dlang/dub/pull/1516

**Comment by finnurthorisson** [comment]
@andre2007 It is not complete. https://github.com/dlang/dub/pull/1516 is about reading D source code from stdin, this issue is about reading the recipe from stdin

@s-ludwig Just see if the first non-white character is `{`. dub.json requires it and SDLang requires you don't do that (`Error: Anonymous tags must have at least one value. They cannot just have children and attributes only.`)
