### ISSUE TITLE
`dub describe` not usable with --cache=local

### ISSUE THREAD

**Issue by dcarp** [dlang/dub#725]
It _wrongly_ downloads the dependencies in the root of the main package and then it exits with an error like:

`memutils (0.4.3) needs to be removed from '<MAIN_PACKAGE_PATH>/memutils-0.4.3' prior placement`

**Comment by s-ludwig** [comment]
`--cache=local` currently is a strange beast and really needs to either be redefined or removed. What it does is to place any downloaded dependencies be placed in the current directory instead of to `~/.dub/packages/`. That doesn't really make much sense in almost all cases and it's basically just a relict of former times.

In this case it sounds like you are really looking for `--skip-registry=all` (avoid any network connections) or `--nodeps` (avoid any dependency resolution attempts)?

**Comment by dcarp** [comment]
`dub` with `--skip-registry=all` or `--nodeps` still needs the dependencies downloaded under `~/.dub/packages`, otherwise it exits with
`Selected package memutils 0.4.3 doesn't exist. Using latest matching version instead.
Could not find a valid dependency tree configuration: 
`
resp.  `Unknown dependency: memutils`

**Comment by s-ludwig** [comment]
Hm, in that case I don't understand the context properly, yet. What exactly are you trying to achieve? `dub describe` always needs to resolve the dependency tree, because the results may depend on something that a dependency defines, and the selection of the build configuration for each package also requires the whole picture.

**Comment by s-ludwig** [comment]
Oh, I've seen your message on the newsgroup now. So you basically want to convert just the package description to JSON, right? This is trivial, be we'll have to add a new command line switch/command for that (together with on-disk conversion in both directions).

**Comment by s-ludwig** [comment]
The thing to consider when going this route, though, is that it will only work for the most simple cases. DUB has to do quite some non-trivial work to properly resolve all build settings to the final values and recreating that in a third party software will not be ideal w.r.t. work required and keeping things in sync.

So I don't know the exact situation, so maybe this doesn't apply, but the suggestion to make this work using `add-path` or `add-local`, or maybe with path based dependencies + a normal `dub describe` is what I'd usually consider the best solution.

**Comment by dcarp** [comment]
Of course that self parsing the package description works just for the simple cases. But this is something that I have under control.

Maybe the best solution is to be able specify the local path when you call `deb describe` (like `dmd -I`). This should be doable. If you are ok with this and you choose the command line arguments name, I can try to make a PR.

**Comment by s-ludwig** [comment]
Sounds like a good opportunity to generalize the `--bare` switch. Maybe we can replace (deprecate) it on that occasion, so that the number of general command line switches doesn't grow more than necessary.

I'd suggest `--search-path=X`, where X can either be a path to a directory, or a path to a directory followed by a wildcard (`path/*`) in which case it will search all sub directories. An empty value could mean to disable all default search paths. `--search-path` would always have precedence over the default search paths and those added with `add-path`/`add-local`.

`--bare` would then be equal to `--search-path= --search-path=*`.

***

Hm, unfortunately `std.getopt` errors out for empty values, so it needs to be something else, but that would be the general idea.

**Comment by WebFreak001** [comment]
no inconsistency with dub describe anymore
