### ISSUE TITLE
dub.selections.json file format should be documented

### ISSUE THREAD

**Issue by dhasenan** [dlang/dub#728]
I haven't been able to find any docs on the format expected by dub.selections.json. The website refers to it, but the actual means of doing so isn't mentioned anywhere.

The outer chrome is relatively obvious. Examining the source briefly (which nobody should have to do in order to use your tool) shows that you can specify a version string or `{"path": "some string"}`, with the implication that that string is a filesystem path.

I've also encountered the following error message:

`WARNING: A deprecated branch based version specification is used for the dependency d-leveldb. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.`

This suggests that there is a way to specify a branch here. How? That's not documented. I can guess, but this really needs to be documented.

**Comment by dhasenan** [comment]
Related: dub.selections.json seems to be automatically generated and seems to pin dependencies to specific versions (~>0.5.0 in dub.json becomes 0.5.2 in dub.selections.json, for instance). When are these updated? I can use `dub upgrade` to "force" an upgrade, but that implies that dub will sometimes perform an upgrade at other times. How often? What will this overwrite?

**Comment by ohdatboi** [comment]
Even though `dub.selections.json` is an auto-generated file which shouldn't be edited manually, here's brief description:

It contains pairs of `"package": <version>` where `<version>` could be either a specific version `"1.0.2"`, a branch `"~master"` (this is deprecated) or a path: `{"path": "../path"}`.
This file contains versions of dependencies used to build your package. That's why `~>0.5.0` which would allow `0.5.1`, `0.5.2` and so on is transformed into an exact version `0.5.2`.

In any case, don't bother and just use `dub upgrade`.
