### ISSUE TITLE
dub fetch <package> --save

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#790]
It would be quite convenient to be able to modify the package.json and `sdl` file and add or update the new package. This is a solution to #789 (multiple package formats).

Expected behavior

1) run `dub fetch <package>` (-> abortion on errors)
2a) When a package is newly installed, add it to the users dependencies
2b) When a package is already installed, but newly "saved" - update its version in the package file.

Ideally - as I expect this command to be posted on the registry - this command should get a nice alias (or even better: without `--save`) like `dub save <package>`.

**Comment by MartinNowak** [comment]
> which is a bit difficult to implement nicely without destroying user formatting in dub.(json/sdl)

Should be easy for dub.sdl b/c it can be appended to the file, for dub.json we'd need to only manipulate the dependencies array (plus detecting leading whitespace).

**Comment by greenify** [comment]
>  for dub.json we'd need to only manipulate the dependencies array

I think json is trivial as there are no comments to preserve. That's why every package manager (npm, bower, ...) just deserializes the file, adds the dependencies and then serializes it back. The best we can do is to detect the pretty-print format (tabs, 2 spaces, 4 spaces, etc.) and use the same option for the newly saved file.

**Comment by s-ludwig** [comment]
Appending for dub.sdl *works* of course, but won't lead to clean results in many cases. Searching for the last top-level "dependency" tag would be okay, though. But you also need to be aware of semicolon separated nodes or backslash line continuations.

JSON, even if it doesn't have comments, has quite some formatting opportunities, see for example <https://github.com/rejectedsoftware/vibe.d/blob/master/dub.json>. Simply deserializing is not an option, IMO. But of course something like what Martin proposed is doable. It's just a little involved and will at least require some modifications to the JSON parser.

In all honesty, I'm still undecided about the net value of this feature. On one hand it kind of makes sense. On the other hand it crosses the border of messing with source files for providing trivial and rather rarely used functionality.

**Comment by greenify** [comment]
> In all honesty, I'm still undecided about the net value of this feature.

Well it's kind of known from other package manager (`bower`, `npm`, `godep`, ...) and it allows a handy command that can be shown on the dub registry and allow easy copy & pasted!

> On the other hand it crosses the border of messing with source files

If there are people out there which really don't like this at all - they can still use `fetch`. It's just an additional, very useful feature.

> and rather rarely used functionality.

95% of the time I run `install` / `fetch` in  a package manager with a package, I actually do want to `save` to to the dependencies too.
Especially when I run this in my package, `fetch` doesn't make so much sense, because I need to add it to my build path anyways.

I would be happy to help out and try to send a PR for this ;-)

**Comment by s-ludwig** [comment]
Is it really more convenient to copy-paste a command line to the console than to copy-paste a dependency line into dub.*? I don't say it is bad, but I don't think it has a particular high value either. Existing habits based on other package managers seems to be the only real argument.

**Comment by greenify** [comment]
> Is it really more convenient to copy-paste a command line to the console than to copy-paste a dependency line into dub.*? 

Well yes - I have to type
1) `vim dub.sdl`
2) `G`, `p`, `:wq`
3) dub

Those are at least 19 keystrokes - and for `json` it's a lot worse ;-)

> Existing habits based on other package managers seems to be the only real argument.

However I do admit that I might be a bit biased after living in the npm universe for quite some time.

**Comment by MartinNowak** [comment]
It's nice to have (and would soon need a `dub fetch <pkg> --save --sub-config bla`), but I agree it's much lower priority than other stuff.

**Comment by ohdatboi** [comment]
Another solution: we don't care about formatting in json and simply deserialize/serialize it. For sdl - just append it to the end of file. In both cases we could check if this dependency already exists, but it isn't necessary since next `dub build` would fail.

 This feature is simple, if not *privimitive* and it'd bring dub closer to the best package managers out there. Can we see at least *some* progress?

**Comment by 0xEAB** [comment]
> we don't care about formatting in json and simply deserialize/serialize it. 

This should be *clearly* stated and documented, otherwise someone will complain soon that this command destroyed their formatting.


> but it isn't necessary since next dub build would fail.

I think it's more user-friendly to actually do check and print an error message.

**Comment by Flying-Toast** [comment]
@wilzbach this was just added with #1587

**Comment by thewilsonator** [comment]
Thanks for the notification.
