### ISSUE TITLE
subConfigurations not working

### ISSUE THREAD

**Issue by dsboger** [dlang/dub#802]
Hello, I'm trying to improve the dynamically-linked build for terminix (https://github.com/gnunn1/terminix/issues/170) and depend on a system-wide installed gtk-d shared libraries. dub.json for terminix has two configurations: the `"default"` links statically and builds gtk-d using dub; the `"dynamic"` configuration uses shared libraries installed in the system, specified in `"libs"` key. It all works, except dub with `--config=dynamic` will still fetch and build gtk-d even if there is a `"subConfigurations"` as follows:

```
"subConfigurations": {
    "gtk-d": "default"
}
```

The command I'm running is: `dub build --build=release --config=dynamic`

Full dub.json:

```
{
    "name": "terminix",
    "description": "A VTE based terminal emulator for Linux",
    "copyright": "Copyright © 2015, Gerald Nunn",
    "authors": ["Gerald Nunn"],
    "buildTypes": {
        "release": {
            "versions": ["StdLoggerDisableTrace"]
        },
        "localize": {
            "versions": ["Localize"]
        }
    },
    "dependencies": {
        "gtk-d": "3.3.0"
    },
    "configurations": [
        {
            "name": "default",
            "targetType": "executable"
       },
        {
            "name": "dynamic",
            "targetType": "executable",    
            "libs": ["gtkd-3", "vted-3"],
            "importPaths": ["/usr/include/d/gtkd-3/"]
        }    
    ],
    "subConfigurations": {
        "gtk-d": "default"
    }
}
```

EDIT: fixed

**Comment by dsboger** [comment]
I'm using latest dub compiled from git master.

**Comment by dsboger** [comment]
I've just seen that I've made the dub.json wrong. If I want the gtk-d dependency to only apply to "default", the entry should be `"gtk-d" : "default"`, but that also does not work. It seems "subConfigurations" is ignored either way.

**Comment by s-ludwig** [comment]
Does this issue still persist? If I understand it right, the "dependencies" field should be moved to the "default" configuration block and the "subConfigurations" field can be removed completely. What "subConfigurations" does is to select a configuration *within* the gtk-d package. Unfortunately there is no error message if the configuration or dependency specified for "subConfigurations" doesn't exist. I think this would make things a lot clearer.

Note that even with the "dependencies" moved inside of the configuration, gtk-d would still be fetched, because dependency resolution happens before configuration resolution. However, it would not be included in the build process anymore.

**Comment by s-ludwig** [comment]
Closing for now. Please re-open if this is still a valid issue.
