### ISSUE TITLE
provide a man page

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub#855]
As dub is getting bigger providing a Linux man page would be a nice to have. Ideally there would be a nice (generic) D tool that can transform all flags into the man page format.

AFAIK it's even mandatory on Debian to provide a man page? - ping @ximion

**Comment by ximion** [comment]
Not mandatory, but a strong "should". Writing manual pages in Troff isn't really much fun, most modern manpages are written in Docbook XML and then transformed to a manpage at compile-time.
That also allows for easily translatable manpages. Creating the manpage from XML is then as easy as running `xmlto man *.xml`.
For Debian, I went the lazy route and auto-generated a manpage from the --help output, but for maintaining this upstream I wouldn't encourage doing that, because first of all the auto-generated output isn't a good manpage and I needed to edit it again, and it also can break at random.
A manpage written directly by humans with useful examples is much more useful.
Maybe dub could even automate the manpage generation via xmlto and install it correctly if `dub install` (issue #839) is implemented.

**Comment by s-ludwig** [comment]
For auto-generation, `dub.commandline` provides an API that can be used to query all the help text in semantic pieces (used to provide the [online docs](http://code.dlang.org/docs/commandline)).

**Comment by ximion** [comment]
That is pretty awesome! But I fear a manpage that is a 1:1 copy of `dub --help` wouldn't be that helpful ^^

**Comment by s-ludwig** [comment]
Probably true ;) But maybe we can combine that in a smart way with some more in-depth documentation. The online documentation still needs that, too.

**Comment by ximion** [comment]
Can Ddoc generate manpages?
FTR, the current manpage we use at Debian can be found here: https://sources.debian.net/src/dub/0.9.24-2/debian/dub.1/ (but as said, it's nothing I would take upstream in that form ^^)

**Comment by EmTee70** [comment]
I have installed via: sudo curl -fsS https://dlang.org/install.sh | bash -s dmd
Is there a manpage now or not? 
Better a short manpage with a link to only documentation than nothing!
Even just the help text is better than:  no manpage found for dub.

**Comment by wilzbach** [comment]
FYI @ all packagers, we now generate man pages automatically - see https://github.com/dlang/dub/pull/1342

> Is there a manpage now or not?

There's, but not shipped with the install scripts at the moment.

**Comment by ximion** [comment]
@wilzbach Good to know, I wasn't aware of that yet - will be added with a later release of the Debian package.

**Comment by Geod24** [comment]
So we now have man pages since #1342 . If they are not shipped with your favorite package manager, open an issue there or here (or both, and link them), for example #1826 .
