### ISSUE TITLE
Launching single-file package with env fails if filename does not end with ".d"

### ISSUE THREAD

**Issue by msoucy** [dlang/dub#910]
Steps to reproduce:
- Make a file named `dtest`, contents:

``` d
#!/usr/bin/env dub
/+ dub.sdl:
    name "tmp"
+/

void main()
{
    import std.stdio : writeln;
    "Hello, dub!".writeln();
}
// vim: ft=d
```
- `chmod +x dubtest`
- `./dubtest`

Problem tested on a Fedora 24 system, with latest dub (eeff313d6e797276f27)

**Comment by s-ludwig** [comment]
This is unfortunately not directly solvable, at least not without another script between dub and the script file. The problem is that the shebang syntax does not generally allow passing additional arguments to the executable, so that `dub <filename>` is all that can be done reliably. But to distinguish D script files from the usual command invocations, looking for ".d" (or *maybe* "/") is the only good option.

Using an additional script that does `dub run --single <filename> -- <additional args>` internally would, however, solve the issue. That only needs to be packaged properly together with the dub executable.

**Comment by jacob-carlborg** [comment]
> The problem is that the shebang syntax does not generally allow passing additional arguments to the executable, so that dub <filename> is all that can be done reliably

It works in the cases I've tried:

```d
$ cat main.d
#!/usr/bin/env dmd -run

void main()
{
    import std.stdio;
    writeln("foo");
}
```
```
$ ./main.d
foo
```

> But to distinguish D script files from the usual command invocations, looking for ".d" (or maybe "/") is the only good option.

Yeah, looking for `/` would be a good addition to the current behavior, then the following would work: `./main`.

An alternative solution would be first check if the a Dub command matches, if it doesn't, treat it as a D file. Although, that might not give the best user experience either.

**Comment by andre2007** [comment]
Solved with pr https://github.com/dlang/dub/pull/1605
Also passing arguments works. See test here
https://github.com/dlang/dub/blob/master/test/issue103-single-file-package.sh#L14
