### ISSUE TITLE
build.sh errors

### ISSUE THREAD

**Issue by timotheecour** [dlang/dub#953]
```
sh build.sh
build.sh: 20: build.sh: cannot open 2.069.0: No such file
build.sh: 20: build.sh: [[: not found
build.sh: 26: build.sh: [[: not found
build.sh: 32: build.sh: [[: not found
Generating version file...
Running dmd...
```
- These are not fatal errors, but why not just replace `sh build.sh` by some `rdmd build.d`, which is much easier to read and maintain?
- Furthermore, inside the script, why not use rdmd instead of `build-files.txt` (DRY)

**Comment by s-ludwig** [comment]
The script requires bash instead of vanilla sh. Using rdmd would be an option if it's reasonable to expect that it's part of every compiler release. But overall I don't see a big advantage that would motivate such a change - bash is available on virtually any Linux installation, as well as on OS X. FreeBSD might be a exception, though, but at least nobody has complained there so far.

**Comment by timotheecour** [comment]
thanks for suggesting bash instead of sh;
this is not a high priority as it works as is, but I still think hardcoding build-files.txt is not DRY (and rdmd is arguably simpler than dub, so it's a reasonable dependency)

**Comment by MartinNowak** [comment]
Addressed by https://github.com/dlang/dub/pull/1252. It's still easier to bootstrap using bash&batch, and since we ship dub as binary nowadays, it's mostly only relevant for us anyhow.
