### ISSUE TITLE
Can't build when code.dlang.org is down

### ISSUE THREAD

**Issue by SingingBush** [dlang/dub#995]
I hit a problem when running `dub build` today with no output. At first I spent some time checking that my dub (installed on OSX via homebrew) had not been screwed up when updating my system. Everything was fine so I decided to `dub -v` and then found that it was taking ages to check for upgrades.

Trying https://code.dlang.org/ in browser is also failing.

So firstly the lack of a message when network is bad is frustrating but also dub waits for ages for each package it looks for. 

It would be good if we can set a config file for dub (something like `~/.dub/config.sdl`) where we could fine tune a timeout property and any other helpful bits.

Also, Is it worth seeing if [Bintray](https://bintray.com/bintray) could mirror packages from the dub repo?

**Comment by MrSmith33** [comment]
> So firstly the lack of a message when network is bad is frustrating but also dub waits for ages for each package it looks for.

This is why I use `--nodeps` cmd flag. Have you tried it yet?

**Comment by SingingBush** [comment]
@MrSmith33 I was not aware of `--nodeps`, I've started using `--skip-registry=all` whenever I recompile.

**Comment by wyrex** [comment]
code.dlang.org shows error 500 and dub doesn't work either.

**Comment by jmh530** [comment]
I am behind a corporate firewall at work and can only fetch packages manually on this computer. So I had not noticed --nodeps before seeing this, but it seems to be very helpful. 

Perhaps the --nodeps part of the help page could make some reference to it being useful as an offline mode as well. Like "Do not check/update dependencies before building. Also useful as an offline mode."

Otherwise, it seems like --nodeps resolves this issue and this could be closed.

**Comment by SingingBush** [comment]
closing this issue as I've created #1468 for the recommendation of a default config file

**Comment by MartinNowak** [comment]
This has been permanently fixed with v1.11.0 see #1509.
