### ISSUE TITLE
Override dependency's dependency version

### ISSUE THREAD

**Issue by JesseKPhillips** [dlang/dub#996]
This is similar to #409 but for the desired package version rather than the library name.

It would be nice to be able to bump a dependency's version of a dependency, such that the dependency can still require a newer dependency.

Example:
https://github.com/forbjok/jsonserialized

This project wraps std_data_json with a simpler API. However std_data_json has been updated so newer compilers don't throw deprecations. Now the jsonserialized package needs its meta data updated and a new version tagged.

Instead I would like to say my project uses jsonserialized and wants std_data_json at version 1.18, later jsonserialized can require 1.19 which my project will use, but until then let me override this version.

https://github.com/forbjok/jsonserialized/pull/3
https://github.com/forbjok/jsonserialized/issues/2

**Comment by s-ludwig** [comment]
You *can* override version selections in the root package by setting dub.selections.json accordingly (DUB will output a warning that the version choice conflicts with the dependency specification in jsonserialized). However, adding a way in the package *recipe* to override dependency choices seems odd to me, since overriding the version would just be a very special case.

The need to override things could also apply to any other recipe property or even to the source code of the dependency itself. And if the author doesn't fix the package in a timely manner, it's always possible to use a private fork.

I realize that this is less convenient than just putting something into the package recipe of the dependent package, but my gut feeling is that keeping a clean boundary like this is much healthier for the package eco system.

**Comment by WebFreak001** [comment]
closing this as dub.selections.json is the current way how to do this for applications.
